name: 'Feature Request'
description: Suggest a feature for the addon

body:
  - type: dropdown
    id: affected-packages
    attributes:
      label: Which scopes are relevant/related to this feature request?
      options:
        - binding
        - addon
      multiple: true

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives considered
    validations:
      required: true
